### ISSUE TITLE
Rebase on the latest AutoValue.

### ISSUE THREAD

**Issue by JakeWharton** [frankiesardo/auto-parcel#13]
The latest AutoValue adds support for builders and value validation. Two things which would make complex parcelables much easier to work with.

Square might be able to do this work in the next few weeks if you do not have the time.

**Comment by frankiesardo** [comment]
Thabks Jake, I'll have a look myself and keep you guys posted.

I'm also considering the idea of adding an explicit dependency to AutoValue and use reflection to inject the Parcelable logic.

**Comment by JakeWharton** [comment]
We have discussed first-party extensibility with the folks at Google who work on AutoValue and have been lobbing ideas back and forth. One of the goals is to solve things like how to solve things like why this library exists, or Gson support, without the need of a fork. I don't think it'll be ready any time soon, though.

**Comment by frankiesardo** [comment]
I'm really considering some help with this, especially if you guys would like to have an artefact published soon. As you see from the [PR](https://github.com/google/auto/pull/87/files) hacking it quickly together is little work, I'm just swamped these weeks.

True extensibility at the annotation processing level is an interesting challenge, I look forward to see what solutions are proposed.

**Comment by felipecsl** [comment]
See #15
