### ISSUE TITLE
Generated getters should be annotated same as declared abstract methods

### ISSUE THREAD

**Issue by xsveda** [frankiesardo/auto-parcel#14]
When I declare an object value and annotate it with `android.support.annotation.NonNull` annotation, there is a null-check generated but the overriding method is not annotated and IDE shows appropriate warning.
**MyObject.java:**
![image](https://cloud.githubusercontent.com/assets/7130807/6103452/ce824750-b044-11e4-9313-8fa237c2041f.png)
**AutoParcel_MyObject.java:**
![image](https://cloud.githubusercontent.com/assets/7130807/6103472/0855431a-b045-11e4-886f-9ba17353a4c1.png)
Is it possible to use same annotation on overriding getters as for declared values?

**Comment by JakeWharton** [comment]
AutoValue does this for methods and they will be doing it for classes soon.

**Comment by frankiesardo** [comment]
If you keep track of this issue I'll notify you when AutoValue master gets merged back

**Comment by frankiesardo** [comment]
See #15
