### ISSUE TITLE
Using auto-parcel removes RoboGuice annotations-database AnnotationDatabaseImpl

### ISSUE THREAD

**Issue by mknudsen** [frankiesardo/auto-parcel#17]
I have a project in which I just included 'com.neenbedankt.gradle.plugins:android-apt:1.4' to the buildscripts classpath, applied `com.neenbedankt.android-apt` as the a gradle plugin, added `com.github.frankiesardo:auto-parcel:0.3` as a compile dependency and `com.github.frankiesardo:auto-parcel-processor:0.3` as apt dependency.

I am also using `org.roboguice:roboguice:3.0.1` for dependency injection. AutoParcel is doing its thing and my unit-tests using the generated classes work just fine. But when I run the app I get the following error: 

    java.lang.ClassNotFoundException: AnnotationDatabaseImpl

Which is a class generated by Guice at compile time to speed up the construction of the dependency graph.  Looking at https://github.com/frankiesardo/auto-parcel/issues/11 which refers to another library generating stuff at compile time: could it be that auto-parcel is overwriting the output of other annotation-processors?

**Comment by xsveda** [comment]
In my case, it was a sideeffect of using `android-apt` plugin.
Just use
`apt 'org.roboguice:roboblender:3.0.1'`
instead of 
`provided 'org.roboguice:roboblender:3.0.1'`

**Comment by mknudsen** [comment]
Thanks, that seems to work. The class now seems to be in place and I can find it at runtime via the classloader.
