### ISSUE TITLE
Annotate generated class methods with @NonNull and @Nullable

### ISSUE THREAD

**Issue by littledot** [frankiesardo/auto-parcel#20]
AutoParcel's generated class methods do not inherit the abstract skeleton's @NonNull and @Nullable annotations. IDEs will then warn developers that "Overriden methods are not annotated".

```java
@AutoParcel
abstract class SomeModel implements Parcelable {
  @NonNull //Overriden methods are not annotated
  abstract String name();
}
```
Can AutoParcel annotate the generated methods with the same annotations?
Thanks.

**Comment by JakeWharton** [comment]
Are you using 0.3? I'm pretty sure this made it in.

**Comment by littledot** [comment]
My bad, I was on 0.2
