### ISSUE TITLE
Error:Could not find com.neenbedankt.gradle.plugins:android-apt:0.3

### ISSUE THREAD

**Issue by 155martinmoreno** [frankiesardo/auto-parcel#23]
I'm getting **Error:Could not find com.neenbedankt.gradle.plugins:android-apt:0.3**

What am I missing?

top level build.gradle:

    buildscript {
        repositories {
            jcenter()
            mavenCentral()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:1.2.3'
            classpath 'com.neenbedankt.gradle.plugins:android-apt:0.3'

            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }

    allprojects {
        repositories {
            jcenter()
            mavenCentral()
        }
    }

module level gradle:

    apply plugin: 'com.android.application'
    apply plugin: 'android-apt'

    android {
        compileSdkVersion 22
        buildToolsVersion "22.0.1"

        defaultConfig {
            applicationId "com.tinchoapps.autoparceltest"
            minSdkVersion 8
            targetSdkVersion 22
            versionCode 1
            versionName "1.0"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile 'com.android.support:appcompat-v7:22.1.1'
        compile 'com.github.frankiesardo:auto-parcel:0.3'
        apt 'com.github.frankiesardo:auto-parcel-processor:0.3'
    }

Thanks in advance

**Comment by artem-zinnatullin** [comment]
Change version of apt plugin in root `build.gradle` to 1.4, `com.neenbedankt.gradle.plugins:android-apt:1.4`

There is no version 0.3 of this plugin in mavenCentral http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.neenbedankt.gradle.plugins%22%20AND%20a%3A%22android-apt%22

**Comment by frankiesardo** [comment]
Updated README

**Comment by 155martinmoreno** [comment]
Great, thanks
(beat me to the README update)
