### ISSUE TITLE
Warning: "@AutoParcel classes cannot have abstract methods other than..."

### ISSUE THREAD

**Issue by hannesstruss** [frankiesardo/auto-parcel#25]
A warning is logged during build whenever I create an AutoParcel-class that implements `Parcelable`: `warning: @AutoParcel classes cannot have abstract methods other than property getters and Builder converters`

Example class:

```java
@AutoParcel
public abstract class TestAutoP implements Parcelable {
  public abstract String name();

  public static TestAutoP create(String name) {
    return new AutoParcel_TestAutoP(name);
  }
}
```

without `Parcelable`, the warning isn't logged. 

Tested with Gradle 2.4, Java 1.8.0_40-ea, starting the build from the commandline.

**Comment by Nimrodda** [comment]
I'm getting the same warnings. When do you plan on making a new release?

**Comment by tomrozb** [comment]
+1

**Comment by frankiesardo** [comment]
0.3.1 released. should be indexed in a couple of hours
