### ISSUE TITLE
Specify which fields to include in equals() and hashCode()

### ISSUE THREAD

**Issue by evelyne24** [frankiesardo/auto-parcel#31]
I couldn't find a way to exclude some fields in the generation of equals() and hashCode() methods but I believe this could be very useful. In my case I had to revert back to using Pojos so I can have control over implementing equals/hashCode. What is your opinion about supporting such functionality?

**Comment by frankiesardo** [comment]
Here's why auto does not support excluding fields to the generated equals and hashcode https://github.com/google/auto/tree/master/value#derived-fields

But as the documentation page says, you can simply write your own hashcode and equals implementation in the abstract class and the generated class will not override them. So you can still use autoparcel without reverting back to pojos.

**Comment by evelyne24** [comment]
Ah great thanks, didn't know it was that simple :)
