### ISSUE TITLE
Annotate generated builder class methods with @NonNull and @Nullable

### ISSUE THREAD

**Issue by Piasy** [frankiesardo/auto-parcel#33]
I'm using 0.3.0, and the generated builder class method not annotated with `@NonNull`/`@Nullable` for its return value and params.

**Comment by ened** [comment]
How would you make a decision which fields are `@NonNull` and `@Nullable`?

**Comment by Piasy** [comment]
@ened I just notice that Android Studio give me this warning. I think this could be achieved var reflection.

**Comment by ened** [comment]
I just test this, and it can work well:

```
  @android.support.annotation.NonNull
  @Override
  public String getLabel() {
    return label;
  }

```

for a method annotated like this:

```
    @NonNull
    public abstract String getLabel();
```

Close this issue?

**Comment by Piasy** [comment]
@ened yes, field works well, but Builder class's method won't annotated.

**Comment by ened** [comment]
Which class method? The constructor?

**Comment by Piasy** [comment]
Like this:
```java
@AutoParcel.Builder
public abstract static class Builder {
        @NonNull
        public abstract Builder login(@NonNull String login);
}
```
But generated code was:
```java
static final class Builder extends GithubUser.Builder {
    @Override
    public GithubUser.Builder login(String login) {
        ...
    }
}
```

**Comment by Ph1b** [comment]
Isn't it possible to also keep the other annotations? 

I often use annotations like `@FloatRange(...)` to define the constraints. So when they are on the (abstract class / interface) builders signature, they should be on the implementation `(AutoParcel_...)` as well.

**Comment by frankiesardo** [comment]
Once the new version of AutoValue is up this library will mimic whatever behaviour AutoValue adopts. I think it does keeps custom annotation (if somebody can confirm please), so hold on tight, as soon as it is release I will upgrade it.

**Comment by frankiesardo** [comment]
AutoParcel now uses the AutoValue extension apis. Please refer to https://github.com/google/auto for implementation and potential issues
