### ISSUE TITLE
Mutable field should make defensive copy in constructor and accessor

### ISSUE THREAD

**Issue by Piasy** [frankiesardo/auto-parcel#34]
Otherwise, the so called 'immutable' object is actually mutable.

Such as the object contains a List, it can modify the items in the List by both using the reference used to build the object, and using the reference get from the accessor.

**Comment by frankiesardo** [comment]
That's a very bad idea. If you supply a mutable ArrayList and I make a defensive copy using an ImmutableLinkedList I destroy all your performance assumptions.

No defensive copies under the hood. If you want immutable collections then supply immutable collections. You can do the defensive copy in the factory method.

**Comment by Piasy** [comment]
Sorry for my lack of deep thought...
