### ISSUE TITLE
Property-Methods in Builder not supported

### ISSUE THREAD

**Issue by fschoellhammer** [frankiesardo/auto-parcel#35]
According to the readme of Google Auto, there should be support for property-methods (e.g. int numberOfLegs()) and autoBuild() method in builders: https://github.com/google/auto/tree/master/value#other-preconditions-or-preprocessing

Auto-Parcel however is still lacking this feature and only allows setters and a build method.

**Comment by frankiesardo** [comment]
Whatever difference in behaviour from google/auto will be erased once auto value extensions apis are out. Not much to do until that happens other than sit tight. Hopefully it won't be a long wait.

**Comment by frankiesardo** [comment]
AutoParcel now uses the AutoValue extension apis. Please refer to https://github.com/google/auto for implementation and potential issues
