### ISSUE TITLE
jcenter?

### ISSUE THREAD

**Issue by chrisjenx** [frankiesardo/auto-parcel#42]
Hey, is there anything wrong with jcenter? I really don't want to be adding yet another repos to my build...

**Comment by frankiesardo** [comment]
I have reasons to use clojars, mainly to tap into clojure libraries that I can depend on instead of copy/pasting code. What's yours for not using a one-liner in your build.gradle?

**Comment by chrisjenx** [comment]
Oh I already have 5 different servers to resolve dependencies, it's getting
a little out of hand. adds to build times when resolving dependencies.
Maybe I should raise the issue with jcenter to mirror clojars?

**Comment by frankiesardo** [comment]
I think you're fighting a battle not worth fighting. How much does it take to resolve one more domain? Milliseconds? And once it's downloaded in your `.m2` folder you don't even have to resolve it again.
