### ISSUE TITLE
Auto-parcel can't compile 'Null' object

### ISSUE THREAD

**Issue by skrzyneckik** [frankiesardo/auto-parcel#43]
@AutoValue with Parcelable interface can't be used for class, which implements all of the abstract methods. Example of use can be Null object in fail-fast approach - a following exception is being thrown on compilation process:

`@AutoValue processor threw an exception: java.lang.IndexOutOfBoundsException`

Here is an example:

    public interface Person {
        String id();
        String firstname();
        String lastname();
        boolean isProvided();

        @AutoValue
        abstract class Empty implements Person, Parcelable {

            public static Empty create() {
                return new AutoValue_Person_Empty();
            }

            @Override
            public String id() {
                throw new UnsupportedOperationException(
                    "there is nothing here"
                );
            }

            @Override
            public String firstname() {
                throw new UnsupportedOperationException(
                    "there is nothing here"
                );
            }

            @Override
            public String lastname() {
                throw new UnsupportedOperationException(
                    "there is nothing here"
                );
            }

            @Override
            public boolean isProvided() {
                return false;
            }
        }
    }

**Comment by frankiesardo** [comment]
Don't override methods. Create an instance instead:

```
public interface Person {
    String id();
    String firstname();
    String lastname();
    boolean isProvided();

    @AutoValue
    abstract class Empty implements Person, Parcelable {
        public static Empty create() {
            return new AutoValue_Person_Empty("id", "firstname", "lastname", false);
        }
    }
}
```
