### ISSUE TITLE
Annotated constructor arguments

### ISSUE THREAD

**Issue by AndreasDahl** [frankiesardo/auto-parcel#45]
The generated constructor does not keep annotations from the original constructor. 

This causes problems with inspections, checking if a @Nullable argument is passed to non-annotated parameters.

**Comment by frankiesardo** [comment]
Could you provide an example please?

**Comment by AndreasDahl** [comment]
With the useful Intellij/AndroidStudio inspection

![screen shot 2016-05-27 at 13 05 39](https://cloud.githubusercontent.com/assets/1443252/15606327/d803c1dc-240b-11e6-9a95-1eb94e62fa3a.png)

the following will produce a warning.

```java
@AutoParcel
@AutoGson(autoParcelClass = AutoParcel_Foo.class)
public abstract class Foo implements Parcelable {
    @NonNull
    public static Foo create(@Nullable Bar bar) {
        return new AutoParcel_Foo(bar); // Will produce a warning
    }

    @Nullable
    public abstract Bar bar();
```

**Comment by frankiesardo** [comment]
Thanks. Are you sure it's an auto-parcel problem and not an auto/value one?

**Comment by AndreasDahl** [comment]
It probably is an auto/value problem.
