### ISSUE TITLE
Doesn't work with annotationProcessor new tag from gradle plugin

### ISSUE THREAD

**Issue by droidpl** [frankiesardo/auto-parcel#47]
The latest gradle plugins start deprecating apt in favor of `annotationProcessor` configuration scope for the android gradle plugin to support the jack and jill compiler. You can test it with `classpath 'com.android.tools.build:gradle:2.2.0-alpha4'`

When the current annotation processor is used, I get the following error:

```
Gradle 'myProject' project refresh failed
Error:Cannot change dependencies of configuration ':demo:_debugAnnotationProcessor' after it has been resolved.
```

Here I paste my gradle config:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"

    defaultConfig {
        applicationId "my.mock.package"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        useJack true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.jakewharton:butterknife:8.1.0'
    compile 'com.android.support:appcompat-v7:24.0.0'
    compile 'com.android.support:recyclerview-v7:24.0.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.1.0'

    //Autovalue
    annotationProcessor 'com.google.auto.value:auto-value:1.3-rc2'
    provided 'com.google.auto.value:auto-value:1.3-rc2'
    annotationProcessor 'frankiesardo:auto-parcel:1.0.3'
}

```

**Comment by ghost** [comment]
+1

**Comment by dulimarta** [comment]
+1

**Comment by Grishberg** [comment]
Try to add next code in build.gradle of your project:

allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}

**Comment by JulienArzul** [comment]
I don't know about the version you were using but it works fine with the android gradle plugin 2.2.2.

@Grishberg was on the right track for your problem I think. In your example, you miss a repository but it's neither jcenter nor mavenCentral.
It seems that the actual AutoParcel library is released on a third repository (seen in the Readme) : 

```
repositories {
  maven {url "https://clojars.org/repo/"}
}
```

**Comment by droidpl** [comment]
I was using `com.android.tools.build:gradle:2.2.0-alpha4` at that moment. About the repository, this is not related to that. In fact you cannot see the repository definition in this script because it is in parent one. The issue was about the `annotationProcessor` gradle configuration in the `dependencies` closure. I would have to test it again to see if it is still happening

**Comment by dpreussler** [comment]
any udpdate here?
I have the same problem with 2.2.2
 :(

**Comment by drayan85** [comment]
+1

**Comment by GathuaKiragu** [comment]
Having the same problem

Here's my build.gradle file 
apply plugin: 'com.android.application'

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion '25.0.0'
    useLibrary 'org.apache.http.legacy'

    repositories {
        mavenCentral()
        jcenter()
    }

    defaultConfig {
        applicationId "com.epicodus.myrestaurants"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildTypes.each {
        it.buildConfigField 'String', 'YELP_CONSUMER_KEY', YelpConsumerKey
        it.buildConfigField 'String', 'YELP_CONSUMER_SECRET', YelpConsumerSecret
        it.buildConfigField 'String', 'YELP_ACCESS_TOKEN', YelpAccessToken
        it.buildConfigField 'String', 'YELP_TOKEN_SECRET', YelpTokenSecret
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }

    androidTestCompile('com.android.support.test:runner:0.3') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    compile 'org.parceler:parceler-api:1.1.6'
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:recyclerview-v7:23.0.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.squareup.okhttp3:okhttp:3.2.0'
    compile 'se.akerfeldt:okhttp-signpost:1.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:support-v4:23.0.1'
    testCompile 'junit:junit:4.12'
    testCompile 'org.robolectric:robolectric:3.0'
    testCompile 'org.robolectric:shadows-support-v4:3.0'
    annotationProcessor 'org.parceler:parcelerr:1.1.6'
}
`

**Comment by andschdk** [comment]
+1

**Comment by PatrickvdGraaf** [comment]
+1

**Comment by mohsin** [comment]
+1

**Comment by amensia** [comment]
+1

**Comment by parthvora25** [comment]
I updated sdk 25 to 26 and this error comes: 
Error:Cannot change dependencies of configuration ':app:_debugAnnotationProcessor' after it has been resolved.
Cannot resolve it.

**Comment by raybechard** [comment]
+1

**Comment by RahulSDeshpande** [comment]
Waiting for the resolution :)

**Comment by 512guanguan** [comment]
gradle 2.3.3 +1

**Comment by droidpl** [comment]
Closed as its been a long time stale
