### ISSUE TITLE
Use with Gson

### ISSUE THREAD

**Issue by f2prateek** [frankiesardo/auto-parcel#6]
Could you annotate your model classes with `AutoValue` when using with Gson? Since Gson uses fields directly, I wasn't sure how it would work.

**Comment by johnkil** [comment]
@frankiesardo what about this issue, can we expect in the near future the implementation based on `GsonSerializationSpec` annotation?

**Comment by frankiesardo** [comment]
@johnkil  I don't think so. But using `@AutoGson` as described [here](https://gist.github.com/JakeWharton/0d67d01badcee0ae7bc9) gets the job done.

**Comment by JakeWharton** [comment]
I think this can be closed since the direction of AutoValue extensions will allow this to be accomplished with composition of extensions.

**Comment by frankiesardo** [comment]
Agree. This is now out of scope.
